import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { motion } from 'framer-motion'
import { ArrowDownToLine, ArrowRight, Check, Gamepad2, Menu, Search, ShieldCheck, Sparkles, Star, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const games = [
  { title: 'Neon Abyss', studio: 'Veilbyte Studio', genre: 'Acción', rating: '4.9', downloads: '12.4k', color: 'from-fuchsia-600 via-purple-700 to-indigo-950', image: 'https://images.unsplash.com/photo-1768933294252-92470e942eea?auto=format&fit=crop&w=1000&q=85', featured: true },
  { title: 'Moss & Moon', studio: 'Soft Lantern', genre: 'Aventura', rating: '4.8', downloads: '8.2k', color: 'from-emerald-600 via-teal-700 to-slate-950', image: 'https://images.unsplash.com/photo-1785122495989-38c1ab6e0adf?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Signal Lost', studio: 'Afterimage', genre: 'Puzzle', rating: '4.7', downloads: '6.8k', color: 'from-orange-500 via-red-700 to-purple-950', image: 'https://images.unsplash.com/photo-1660507224958-729c18ba1277?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Tiny Astronauts', studio: 'Orbit Picnic', genre: 'Casual', rating: '4.9', downloads: '5.1k', color: 'from-sky-500 via-blue-700 to-violet-950', image: 'https://images.unsplash.com/photo-1784969293884-8d3afcff1a13?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Paper Kingdom', studio: 'Folded Worlds', genre: 'RPG', rating: '4.8', downloads: '4.7k', color: 'from-amber-400 via-orange-600 to-rose-950', image: 'https://images.unsplash.com/photo-1778856922213-dcecd79354c9?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Garden Protocol', studio: 'Quiet Signal', genre: 'Simulación', rating: '4.6', downloads: '3.9k', color: 'from-lime-500 via-emerald-700 to-cyan-950', image: 'https://images.unsplash.com/photo-1668119065849-d8a7e9d73a7b?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Afterglow FM', studio: 'Midnight Arcade', genre: 'Narrativa', rating: '4.9', downloads: '3.4k', color: 'from-violet-500 via-pink-700 to-slate-950', image: 'https://images.unsplash.com/photo-1779262553053-70215cd9e070?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Pixel Pilgrims', studio: 'Small Giant Games', genre: 'Plataformas', rating: '4.7', downloads: '2.8k', color: 'from-cyan-400 via-blue-700 to-indigo-950', image: 'https://images.unsplash.com/photo-1768933294578-02022bfb7532?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Static Hearts', studio: 'North Loop', genre: 'Rompecabezas', rating: '4.8', downloads: '2.3k', color: 'from-rose-500 via-red-700 to-orange-950', image: 'https://images.unsplash.com/photo-1660507224958-729c18ba1277?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Moonbase 17', studio: 'Low Orbit Club', genre: 'Estrategia', rating: '4.5', downloads: '1.9k', color: 'from-slate-500 via-indigo-800 to-purple-950', image: 'https://images.unsplash.com/photo-1784969293884-8d3afcff1a13?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'Café Comet', studio: 'Daydream Dept.', genre: 'Relax', rating: '4.9', downloads: '1.6k', color: 'from-yellow-400 via-amber-600 to-fuchsia-950', image: 'https://images.unsplash.com/photo-1785122495989-38c1ab6e0adf?auto=format&fit=crop&w=1000&q=85', featured: false },
  { title: 'The Last Lantern', studio: 'Ember House', genre: 'Terror', rating: '4.6', downloads: '1.2k', color: 'from-red-600 via-purple-800 to-slate-950', image: 'https://images.unsplash.com/photo-1768933294252-92470e942eea?auto=format&fit=crop&w=1000&q=85', featured: false },
]

const upcomingGames = [
  { title: 'Lunar Bloom', studio: 'Mothlight Studio', genre: 'Aventura narrativa', date: 'Octubre 2026', image: 'https://images.unsplash.com/photo-1779262553053-70215cd9e070?auto=format&fit=crop&w=1000&q=85', color: 'from-violet-500 to-indigo-950' },
  { title: 'Circuit Breakers', studio: 'Voltage Kids', genre: 'Acción cooperativa', date: 'Noviembre 2026', image: 'https://images.unsplash.com/photo-1768933294578-02022bfb7532?auto=format&fit=crop&w=1000&q=85', color: 'from-cyan-400 to-blue-950' },
  { title: 'Wilderfolk', studio: 'Fern & Fox', genre: 'RPG de exploración', date: 'Diciembre 2026', image: 'https://images.unsplash.com/photo-1785122495989-38c1ab6e0adf?auto=format&fit=crop&w=1000&q=85', color: 'from-emerald-500 to-teal-950' },
]

export const Route = createFileRoute('/')({
  head: () => ({ meta: [{ title: 'Nicho · Juegos indie fuera de las tiendas' }, { name: 'description', content: 'Descubre y descarga juegos indie únicos, seguros y fuera de las tiendas mainstream.' }] }),
  component: Home,
})

function Home() {
  const [query, setQuery] = useState('')
  const [menuOpen, setMenuOpen] = useState(false)
  const filteredGames = useMemo(() => games.filter((game) => `${game.title} ${game.genre} ${game.studio}`.toLowerCase().includes(query.toLowerCase())), [query])
  const scrollToGames = () => document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' })

  return (
    <main className="min-h-dvh overflow-hidden bg-background">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8" aria-label="Navegación principal">
        <a href="#top" className="flex items-center gap-2.5 font-bold tracking-tight text-foreground"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><Gamepad2 className="size-5" /></span><span className="text-xl">nicho<span className="text-accent">.</span></span></a>
        <div className="hidden items-center gap-8 text-sm font-medium text-muted-foreground md:flex"><a className="transition-colors hover:text-foreground" href="#explore">Explorar</a><a className="transition-colors hover:text-foreground" href="#upcoming">Próximamente</a><a className="transition-colors hover:text-foreground" href="#curated">Selección curada</a><a className="transition-colors hover:text-foreground" href="#about">Sobre Nicho</a></div>
        <div className="flex items-center gap-3"><button className="hidden text-sm font-semibold text-primary transition-transform hover:-translate-y-0.5 sm:block" onClick={() => alert('La cuenta de desarrolladores estará disponible pronto.')}>Publica tu juego</button><Button className="hidden rounded-full bg-primary px-5 shadow-md shadow-primary/20 hover:scale-[1.03] sm:inline-flex" onClick={scrollToGames}>Descubrir juegos</Button><button className="grid size-10 place-items-center rounded-full border border-border text-foreground md:hidden" aria-label="Abrir menú" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></div>
      </nav>
      {menuOpen && <div className="mx-5 flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 text-sm font-semibold shadow-lg md:hidden"><a href="#explore" onClick={() => setMenuOpen(false)}>Explorar</a><a href="#upcoming" onClick={() => setMenuOpen(false)}>Próximamente</a><a href="#curated" onClick={() => setMenuOpen(false)}>Selección curada</a><a href="#about" onClick={() => setMenuOpen(false)}>Sobre Nicho</a></div>}

      <section id="top" className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-12 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:pb-28 lg:pt-20">
        <div className="relative z-10 max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-accent/30 bg-accent/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-primary"><Sparkles className="size-3.5" /> El rincón de lo diferente</div><h1 className="font-serif text-5xl leading-[0.98] tracking-[-0.04em] text-foreground sm:text-7xl lg:text-[5.5rem]">Juegos con<br /><span className="italic text-primary">otra historia.</span></h1><p className="mt-7 max-w-md text-lg leading-relaxed text-muted-foreground">Descubre pequeñas obras maestras que viven fuera de las tiendas de siempre. Hechas con obsesión, compartidas contigo.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button className="h-12 rounded-full bg-primary px-7 text-base shadow-xl shadow-primary/20 transition-transform hover:scale-[1.03]" onClick={scrollToGames}>Explorar la colección <ArrowRight className="size-4" /></Button><button className="h-12 rounded-full border border-border px-6 text-sm font-semibold text-foreground transition-colors hover:bg-secondary" onClick={() => alert('Nicho verifica cada descarga y cada estudio antes de recomendarlo.')}>¿Cómo funciona?</button></div><div className="mt-10 flex items-center gap-4 text-xs text-muted-foreground"><div className="flex -space-x-2"><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-accent font-bold text-accent-foreground">M</span><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-primary text-primary-foreground">S</span><span className="grid size-8 place-items-center rounded-full border-2 border-background bg-secondary font-bold text-primary">+</span></div><span><strong className="text-foreground">2,400+</strong> jugadores ya están dentro</span></div></div>
        <div className="relative min-h-[470px] lg:min-h-[600px]"><div className="absolute -right-12 top-8 h-72 w-72 rounded-full bg-accent/20 blur-3xl" /><div className="absolute bottom-0 left-4 h-80 w-80 rounded-full bg-primary/15 blur-3xl" /><motion.div initial={{ opacity: 0, y: 24, rotate: 3 }} animate={{ opacity: 1, y: 0, rotate: 0 }} transition={{ duration: 0.7 }} className="absolute right-0 top-4 h-[410px] w-[82%] overflow-hidden rounded-[2rem] border-8 border-card bg-card shadow-2xl shadow-primary/20 sm:h-[500px] lg:h-[570px]"><img src={games[0].image} alt="Arte colorido de Neon Abyss" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-primary/90 via-transparent to-transparent" /><div className="absolute bottom-0 left-0 right-0 p-7 text-primary-foreground"><span className="text-xs font-bold uppercase tracking-[0.18em] text-accent">Juego destacado · 01</span><h2 className="mt-2 font-serif text-4xl italic">Neon Abyss</h2><p className="mt-1 text-sm text-primary-foreground/75">Una aventura que no pide permiso.</p></div></motion.div><div className="absolute bottom-2 left-0 rounded-2xl border border-border bg-card/95 p-4 shadow-xl backdrop-blur-sm sm:bottom-12"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-accent/20 text-accent-foreground"><ShieldCheck className="size-5" /></div><div><p className="text-sm font-bold text-foreground">Descargas verificadas</p><p className="text-xs text-muted-foreground">Sin sorpresas. Solo juegos.</p></div></div></div><div className="absolute right-0 top-1/2 rounded-xl border border-border bg-card px-4 py-3 shadow-xl"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Valoración</p><p className="mt-1 flex items-center gap-1 font-bold text-foreground"><Star className="size-4 fill-accent text-accent" /> 4.9 / 5</p></div></div>
      </section>

      <section id="explore" className="border-y border-border bg-secondary/40 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-primary">La colección</p><h2 className="font-serif text-4xl tracking-tight text-foreground sm:text-5xl">Encuentra tu próximo <span className="italic text-primary">favorito.</span></h2></div><div className="relative w-full md:w-72"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busca por nombre o género..." className="h-11 rounded-full border-border bg-card pl-11" /></div></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filteredGames.map((game, index) => <GameCard key={game.title} game={game} index={index} />)}</div>{filteredGames.length === 0 && <p className="py-12 text-center text-muted-foreground">No encontramos ese juego todavía. Prueba con otro nombre.</p>}</div></section>

      <section id="curated" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-accent-foreground">Más que una descarga</p><h2 className="font-serif text-4xl leading-tight tracking-tight text-foreground sm:text-5xl">El buen juego<br /><span className="italic text-primary">merece un lugar.</span></h2><p className="mt-6 max-w-sm leading-relaxed text-muted-foreground">No somos un escaparate infinito. Somos ese amigo que juega demasiado y te pasa solo lo que de verdad vale la pena.</p><button className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline" onClick={() => alert('La selección se actualiza cada semana.')}>Conoce nuestro criterio <ArrowRight className="size-4" /></button></div><div id="about" className="grid gap-4 sm:grid-cols-2"><InfoBlock icon={<ShieldCheck />} title="Primero, seguros" text="Revisamos cada archivo y cada creador antes de ponerlo en tus manos." /><InfoBlock icon={<Sparkles />} title="Siempre diferentes" text="Ideas frescas, mecánicas raras y mundos que no caben en una categoría." /><InfoBlock icon={<Gamepad2 />} title="Hechos por personas" text="Conoce a los estudios detrás del juego y apóyalos directamente." /><InfoBlock icon={<ArrowDownToLine />} title="Sin fricción" text="Descarga directa, instrucciones claras y cero ruido en el camino." /></div></section>
      <footer className="border-t border-border bg-primary px-5 py-10 text-primary-foreground lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-2 font-bold"><span className="grid size-8 place-items-center rounded-lg bg-accent text-accent-foreground"><Gamepad2 className="size-4" /></span> nicho<span className="text-accent">.</span></div><p className="text-sm text-primary-foreground/70">Un hogar para los juegos que se salen del mapa.</p><p className="text-xs text-primary-foreground/50">© 2024 Nicho</p></div></footer>
    </main>
  )
}

function GameCard({ game, index }: { game: typeof games[number]; index: number }) {
  const [downloaded, setDownloaded] = useState(false)
  return <motion.article initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="group overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"><div className={`relative h-48 overflow-hidden bg-gradient-to-br ${game.color}`}><img src={game.image} alt={`Arte de ${game.title}`} className="h-full w-full object-cover opacity-75 mix-blend-screen transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-card/90 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-foreground">{game.genre}</span><span className="absolute right-3 top-3 flex items-center gap-1 rounded-full bg-foreground/80 px-2.5 py-1 text-[10px] font-bold text-background"><Star className="size-3 fill-accent text-accent" /> {game.rating}</span></div><div className="p-5"><h3 className="font-serif text-2xl text-foreground">{game.title}</h3><p className="mt-1 text-xs text-muted-foreground">por {game.studio}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs text-muted-foreground">{game.downloads} descargas</span><button aria-label={`Descargar ${game.title}`} onClick={() => setDownloaded(true)} className="grid size-10 place-items-center rounded-full bg-primary text-primary-foreground shadow-md transition-transform hover:scale-105 active:scale-95">{downloaded ? <Check className="size-4" /> : <ArrowDownToLine className="size-4" />}</button></div>{downloaded && <p className="mt-3 text-xs font-semibold text-primary">¡Listo! Tu descarga comienza ahora.</p>}</div></motion.article>
}

function InfoBlock({ icon, title, text }: { icon: ReactNode; title: string; text: string }) {
  return <div className="rounded-2xl border border-border bg-secondary/40 p-6 transition-colors hover:bg-secondary"><div className="mb-5 grid size-11 place-items-center rounded-xl bg-accent/20 text-accent-foreground">{icon}</div><h3 className="font-semibold text-foreground">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>
}
